
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

#path del file di log
log.path = C:/temp/

#configurazione per l'ottenimento dell' Access Token
token.url=https://idptest.regione.liguria.it/oauth2/token
authorization.header=Basic M2ZoZHRpcllEOTBBek1ncGRBNFBQQVVYS0FNYTptajlJZmFtOEtxenlOQzRQRVJmM3JuZ0YwZFFh

#certificati per la mTLS
#path.FileP12 = /WEB-INF/A1111TOPGATEXXXX_auth.pem
path.FileP12 = /WEB-INF/fascicolosanitario-api-test.regione.liguria.it_1027d430ec1e2d4ea18dcdc2d1f5fa93813a289e.p12
passwordTLS = z!F#*mF+3j72
ssl.keystore.password = z!F#*mF+3j72
#file .pem per la cifratura del token JWT
pem.LDO = /WEB-INF/S1111TOPGATEXXXX_sign.pem
pem.CERT_VACC_SKIPPER = /WEB-INF/S1111TOPGATEXXXX_sign.pem
pem.SING_VACC_SKIPPER = /WEB-INF/S1111TOPGATEXXXX_sign.pem
pem.SING_VACC_PHTRACK = /WEB-INF/S1070105000000XX_sign.pem
pem.CERT_VACC = /WEB-INF/S1070105000000XX_sign.pem
pem.SING_VACC = /WEB-INF/S1070105000000XX_sign.pem

#file .p12 per la cifratura del token JWT
p12.LDO = /WEB-INF/firmaTopgate.p12
p12.CERT_VACC_SKIPPER = /WEB-INF/firmaTopgate.p12
p12.SING_VACC_SKIPPER = /WEB-INF/firmaTopgate.p12
p12.SING_VACC_PHTRACK = /WEB-INF/S1070105000000XX.pfx
p12.CERT_VACC = /WEB-INF/S1070105000000XX.pfx
p12.SING_VACC = /WEB-INF/S1070105000000XX.pfx